import { cp, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { expect, test, type Page } from "@playwright/test";
import { createProjectProxy, type ProjectProxy } from "../../packages/dev-server/src/index.js";
import { reservePort } from "../helpers/port-probe.js";
import { startViteDemo, type ManagedProcess } from "../helpers/process-harness.js";
import { projectRoot } from "../helpers/paths.js";

const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
let copyRoot: string | undefined; let demo: ManagedProcess | undefined; let proxy: ProjectProxy | undefined; let upstream = "";

async function proxyUrl(): Promise<string> { proxy = createProjectProxy(upstream, { projectRoot: copyRoot, captureHistoryScreenshot: async () => png, project: { id: "phase11_vanilla", name: "Phase 11 vanilla", framework: "vanilla", capabilities: { canExplore: true, canWriteSource: true } } }); return (await proxy.listen()).url; }
async function start(): Promise<string> { const base = path.join(projectRoot, ".reframe-test-artifacts", "phase11-e2e"); await mkdir(base, { recursive: true }); copyRoot = await mkdtemp(path.join(base, "vanilla-")); await cp(path.join(projectRoot, "demo", "vanilla-demo"), copyRoot, { recursive: true }); await rm(path.join(copyRoot, ".reframe"), { recursive: true, force: true }); const port = await reservePort(); await port.release(); demo = await startViteDemo(copyRoot, port.port); upstream = `http://127.0.0.1:${port.port}/`; return proxyUrl(); }
async function ready(page: Page, url?: string): Promise<void> { if (url) await page.goto(url, { waitUntil: "domcontentloaded" }); await expect(page.locator("#reframe-root")).toHaveAttribute("data-reframe-state", "connected", { timeout: 10_000 }); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].annotationState)).toBeTruthy(); }
async function selectAnnual(page: Page): Promise<void> { if (!await page.evaluate(() => window[Symbol.for("reframe.browser-client")].selectMode)) await page.locator("#reframe-root [data-reframe-select]").click(); await page.locator("#card-annual").click(); await expect(page.locator("#reframe-root [data-reframe-mapping]")).toHaveText("exact"); }
async function addComment(page: Page, comment: string): Promise<string> { await selectAnnual(page); await page.locator("#reframe-root [data-reframe-comments]").click(); await expect(page.locator("#reframe-root [data-reframe-annotation-form]")).toBeVisible(); await page.locator("#reframe-root [data-reframe-annotation-author]").fill("Avery Reviewer"); await page.locator("#reframe-root [data-reframe-annotation-comment]").fill(comment); await page.locator("#reframe-root [data-reframe-annotation-highlight]").check(); await page.locator("#reframe-root [data-reframe-annotation-form]").evaluate((form: HTMLFormElement) => form.requestSubmit()); await expect(page.locator("#reframe-root [data-reframe-diagnostic]")).toContainText("ANNOTATION_CREATED"); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].annotationState.annotations.length)).toBe(1); await page.locator("#reframe-root [data-reframe-annotation-close]").click(); await expect(page.locator("#reframe-root .annotation-pin")).toHaveCount(1); return page.evaluate(() => window[Symbol.for("reframe.browser-client")].annotationState.annotations[0].id); }
async function action(page: Page, comment: string, label: "Resolve" | "Reopen"): Promise<void> { await page.evaluate(() => window[Symbol.for("reframe.browser-client")].openCommentsList()); const item = page.locator("#reframe-root .annotation-item", { hasText: comment }); await item.getByRole("button", { name: label }).click(); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].annotationState.annotations[0]?.status)).toBe(label === "Resolve" ? "resolved" : "open"); await page.locator("#reframe-root [data-reframe-annotation-close]").click(); }
async function apply(page: Page, width: number): Promise<void> { await selectAnnual(page); const before = await page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.currentId); await page.evaluate((value) => window[Symbol.for("reframe.browser-client")].previewWidth(value), width); await page.locator("#reframe-root [data-reframe-apply]").click(); await expect(page.locator("#reframe-root [data-reframe-diagnostic]")).toContainText("Saved to source", { timeout: 15_000 }); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.currentId)).not.toBe(before); }
async function restart(page: Page): Promise<void> { await proxy?.close(); proxy = undefined; const url = await proxyUrl(); await ready(page, url); }

test.afterEach(async () => { await proxy?.close(); proxy = undefined; await demo?.stop(); demo = undefined; if (copyRoot) await rm(copyRoot, { recursive: true, force: true, maxRetries: 20, retryDelay: 50 }); copyRoot = undefined; });

test("P11-01 creates one mapped pin/comment/highlight and restores it on the correct card after restart", async ({ page }) => { const url = await start(); await ready(page, url); const sourceBefore = await readFile(path.join(copyRoot!, "style.css")); const id = await addComment(page, "Make the annual card easier to scan."); const folder = path.join(copyRoot!, ".reframe", "annotations"); const files = (await readdir(folder)).filter((name) => name.endsWith(".json")); expect(files).toEqual([`${id}.json`]); const saved = JSON.parse(await readFile(path.join(folder, files[0]!), "utf8")); expect(saved).toMatchObject({ schemaVersion: 1, id, author: "Avery Reviewer", component: "article#card-annual", route: "/", status: "open", anchorConfidence: "exact", highlight: { x: 0, y: 0, width: 1, height: 1 } }); expect(await readFile(path.join(copyRoot!, "style.css"))).toEqual(sourceBefore); await restart(page); await expect(page.locator("#reframe-root .annotation-pin")).toHaveCount(1); const pin = page.locator("#reframe-root .annotation-pin"); await expect(pin).toHaveAttribute("aria-label", /Avery Reviewer.*article#card-annual/); await expect(page.locator("#reframe-root .annotation-highlight")).toHaveCount(1); });

test("P11-02 resolve and reopen update only that file and survive restart with thread text intact", async ({ page }) => { const comment = "Keep this pricing choice visible."; const url = await start(); await ready(page, url); const sourceBefore = await readFile(path.join(copyRoot!, "style.css")); const id = await addComment(page, comment); const file = path.join(copyRoot!, ".reframe", "annotations", `${id}.json`); await action(page, comment, "Resolve"); expect(JSON.parse(await readFile(file, "utf8"))).toMatchObject({ status: "resolved", comment, history: [{ action: "created" }, { action: "resolved" }] }); await restart(page); await expect(page.locator("#reframe-root .annotation-pin")).toHaveCount(0); await action(page, comment, "Reopen"); const reopened = JSON.parse(await readFile(file, "utf8")); expect(reopened).toMatchObject({ status: "open", comment, history: [{ action: "created" }, { action: "resolved" }, { action: "reopened" }] }); expect((await readdir(path.dirname(file))).filter((name) => name.endsWith(".json"))).toEqual([`${id}.json`]); expect(await readFile(path.join(copyRoot!, "style.css"))).toEqual(sourceBefore); await restart(page); await expect(page.locator("#reframe-root .annotation-pin")).toHaveCount(1); });

test("P11-15 annotations coexist with Direct Edit, HMR, restore, and history comparison without duplication or source writes", async ({ page }) => { const comment = "Preserve this card emphasis."; const url = await start(); await ready(page, url); const sourceBeforeComment = await readFile(path.join(copyRoot!, "style.css")); await addComment(page, comment); expect(await readFile(path.join(copyRoot!, "style.css"))).toEqual(sourceBeforeComment); await apply(page, 420); const edited = await readFile(path.join(copyRoot!, "style.css")); await action(page, comment, "Resolve"); await action(page, comment, "Reopen"); expect(await readFile(path.join(copyRoot!, "style.css"))).toEqual(edited); await expect(page.locator("#reframe-root .annotation-pin")).toHaveCount(1); const indexFile = path.join(copyRoot!, "index.html"); await writeFile(indexFile, `${await readFile(indexFile, "utf8")}\n`); await page.waitForEvent("load"); await ready(page); await expect(page.locator("#reframe-root .annotation-pin")).toHaveCount(1); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.canRestore), { timeout: 15_000 }).toBe(true); await page.evaluate(async () => { const api = window[Symbol.for("reframe.browser-client")]; await api.showPrevious(); api.hidePrevious(); }); expect(await readFile(path.join(copyRoot!, "style.css"))).toEqual(edited); page.once("dialog", (dialog) => dialog.accept()); await page.evaluate(() => window[Symbol.for("reframe.browser-client")].restorePrevious()); await ready(page); await expect.poll(() => readFile(path.join(copyRoot!, "style.css"))).toEqual(sourceBeforeComment); await expect(page.locator("#reframe-root .annotation-pin")).toHaveCount(1); expect((await readdir(path.join(copyRoot!, ".reframe", "annotations"))).filter((name) => name.endsWith(".json"))).toHaveLength(1); await expect(page.locator("#reframe-root")).toHaveCount(1); });

