import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { expect, test, type Browser } from "@playwright/test";
import { createFakeCodexProvider, createProjectProxy, type ContextPacket, type ProjectProxy } from "../../packages/dev-server/src/index.js";
import { reservePort } from "../helpers/port-probe.js";
import { startViteDemo, type ManagedProcess } from "../helpers/process-harness.js";
import { projectRoot } from "../helpers/paths.js";

let copyRoot: string | undefined; let demo: ManagedProcess | undefined; let proxy: ProjectProxy | undefined;
test.afterEach(async () => { await proxy?.close(); proxy = undefined; await demo?.stop(); demo = undefined; if (copyRoot) await rm(copyRoot, { recursive: true, force: true, maxRetries: 20, retryDelay: 50 }); copyRoot = undefined; });

function chunk(type: string, data = Buffer.alloc(0)): Buffer { const head = Buffer.alloc(8); head.writeUInt32BE(data.length); head.write(type, 4, "ascii"); return Buffer.concat([head, data, Buffer.alloc(4)]); }
function syntheticReference(): Buffer { const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(1280); ihdr.writeUInt32BE(720, 4); ihdr[8] = 8; ihdr[9] = 2; return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk("IHDR", ihdr), chunk("IDAT"), chunk("IEND")]); }

async function screenshot(browser: Browser, url: string, width = 1280): Promise<Buffer> { const page = await browser.newPage({ viewport: { width, height: 900 } }); try { await page.goto(url, { waitUntil: "domcontentloaded" }); return await page.screenshot({ fullPage: true }); } finally { await page.close(); } }
async function selectTarget(page: import("@playwright/test").Page): Promise<void> { await expect(page.locator("#reframe-root")).toHaveAttribute("data-reframe-state", "connected", { timeout: 10_000 }); await page.locator("#reframe-root [data-reframe-select]").click(); await page.locator("#card-annual").click(); await expect(page.locator("#reframe-root [data-reframe-mapping]")).toHaveText("exact"); }
async function freezePlan(page: import("@playwright/test").Page, file: string): Promise<void> {
  await page.locator("#reframe-root [data-reframe-reference]").click(); await expect(page.locator("#reframe-root [data-reframe-reference-dialog]")).toBeVisible(); await expect(page.locator("#reframe-root [data-reframe-reference-brand]")).toHaveValue("preserve"); await page.locator("#reframe-root [data-reframe-reference-file]").setInputFiles(file); await page.locator('#reframe-root [data-reframe-reference-choices] input[value="page-structure"]').check(); await page.locator('#reframe-root [data-reframe-reference-choices] input[value="component-arrangement"]').check(); await page.locator("#reframe-root [data-reframe-reference-placement]").fill("Replace the current card arrangement on this page"); await page.locator("#reframe-root [data-reframe-reference-build]").click(); await expect(page.locator("#reframe-root [data-reframe-reference-status]")).toContainText("Review the complete plan"); const plan = page.locator("#reframe-root [data-reframe-reference-plan]"); await expect(plan).toContainText('"page-structure"'); await expect(plan).toContainText('"component-arrangement"'); await expect(plan).toContainText('"colors"'); await expect(plan).toContainText('"prohibitedCopy"'); await page.locator("#reframe-root [data-reframe-reference-freeze]").click(); await expect(page.locator("#reframe-root [data-reframe-reference-status]")).toContainText("Plan frozen:"); await page.locator("#reframe-root [data-reframe-reference-close]").click();
}

test("P12-14/P12-01 official preserve-brand reference flow is screenshot-first, reversible, and checkpointed", async ({ page, browser }) => {
  const base = path.join(projectRoot, ".reframe-test-artifacts", "phase12-e2e"); await mkdir(base, { recursive: true }); copyRoot = await mkdtemp(path.join(base, "vanilla-")); await cp(path.join(projectRoot, "demo", "vanilla-demo"), copyRoot, { recursive: true }); const css = path.join(copyRoot, "style.css"); const original = await readFile(css); const referenceFile = path.join(copyRoot, "synthetic-dashboard.png"); await writeFile(referenceFile, syntheticReference());
  const port = await reservePort(); await port.release(); demo = await startViteDemo(copyRoot, port.port); const upstream = `http://127.0.0.1:${port.port}/`; const packets: ContextPacket[] = [];
  const provider = createFakeCodexProvider(async (packet, context) => { packets.push(packet); return { generationId: context.generationId, conversationId: context.conversationId, changes: [{ path: packet.source.path, expectedHash: packet.source.hash, before: packet.source.snippet, after: `${packet.source.snippet}\n#pricing-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }\n` }] }; });
  proxy = createProjectProxy(upstream, { projectRoot: copyRoot, aiProvider: provider, captureHistoryScreenshot: async (_stage, context) => screenshot(browser, new URL(context.request.fingerprint.route, upstream).href), verifyResponsive: async (route, widths) => { const results = []; for (const width of widths) { const current = await browser.newPage({ viewport: { width, height: 900 } }); try { await current.goto(new URL(route, upstream).href, { waitUntil: "domcontentloaded" }); const overflow = await current.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1); results.push({ width, passed: !overflow, findings: overflow ? ["horizontal overflow"] : [] }); } finally { await current.close(); } } return results; }, project: { id: "phase12_vanilla", name: "Phase 12 vanilla", framework: "vanilla", capabilities: { canExplore: true, canWriteSource: true } } });
  const url = (await proxy.listen()).url; await page.goto(url, { waitUntil: "domcontentloaded" }); await selectTarget(page); await freezePlan(page, referenceFile);
  await page.locator("#reframe-root [data-reframe-generate]").click(); await page.locator("#reframe-root [data-reframe-ai-prompt]").fill("Borrow only the approved structure and arrangement."); await page.locator("#reframe-root [data-reframe-generate]").click(); await expect(page.locator("#reframe-root [data-reframe-ai-status]")).toContainText("review", { timeout: 15_000 }); expect(packets).toHaveLength(1); expect(Object.keys(packets[0]!.reference!.evidence)).toEqual(["page-structure", "component-arrangement"]); expect(packets[0]!.reference!.plan.brand).toBe("preserve"); expect(packets[0]!.reference!.plan.preserved).toContain("colors");
  await page.locator("#reframe-root [data-reframe-ai-compare]").click(); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeVisible(); await expect(page.locator("#reframe-root [data-reframe-time-image]")).toHaveAttribute("src", /^blob:/); await page.keyboard.press("Escape"); await page.locator("#reframe-root [data-reframe-ai-reject]").click(); await expect.poll(() => readFile(css)).toEqual(original);
  await page.reload({ waitUntil: "domcontentloaded" }); await selectTarget(page); await freezePlan(page, referenceFile); await page.locator("#reframe-root [data-reframe-generate]").click(); await page.locator("#reframe-root [data-reframe-ai-prompt]").fill("Borrow only the approved structure and arrangement."); await page.locator("#reframe-root [data-reframe-generate]").click(); await expect(page.locator("#reframe-root [data-reframe-ai-status]")).toContainText("review", { timeout: 15_000 }); await page.locator("#reframe-root [data-reframe-ai-accept]").click(); await expect(page.locator("#reframe-root [data-reframe-ai-status]")).toContainText("accepted", { timeout: 15_000 });
  const historyRoot = path.join(copyRoot, ".reframe", "history"); const entries = await import("node:fs/promises").then(({ readdir }) => readdir(historyRoot, { withFileTypes: true })); let metadata: Record<string, any> | undefined; for (const entry of entries) { if (!entry.isDirectory() || entry.name.startsWith(".")) continue; const value = JSON.parse(await readFile(path.join(historyRoot, entry.name, "metadata.json"), "utf8")); if (value.ai?.reference) metadata = value; } expect(metadata?.ai.reference).toMatchObject({ selectedTraits: ["page-structure", "component-arrangement"], brandTreatment: "preserve" }); expect(metadata!.ai.reference.responsive.map((item: { width: number }) => item.width)).toEqual([375, 768, 1280]); expect(metadata!.screenshots.visualComplete).toBe(true); expect(await readFile(css, "utf8")).toContain("grid-template-columns");
});
