import { cp, mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { expect, test, type Page } from "@playwright/test";
import { createHistoryStore, createProjectProxy, type ProjectProxy, type ProjectProxyOptions } from "../../packages/dev-server/src/index.js";
import { createBrowserScreenshotCapture } from "../../packages/cli/src/screenshot-capture.js";
import { reservePort } from "../helpers/port-probe.js";
import { startViteDemo, type ManagedProcess } from "../helpers/process-harness.js";
import { projectRoot } from "../helpers/paths.js";

const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
const otherPng = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=", "base64");
let copyRoot: string | undefined; let demo: ManagedProcess | undefined; let proxy: ProjectProxy | undefined; let captureBrowser: ReturnType<typeof createBrowserScreenshotCapture> | undefined;

async function seedHistory(root: string, count: number): Promise<void> {
  const bytes = await readFile(path.join(root, "style.css")); const history = createHistoryStore({ projectRoot: root, captureScreenshot: async () => png });
  for (let index = 0; index < count; index += 1) await history.createCheckpoint({
    files: [{ relativePath: "style.css", beforeBytes: bytes, afterBytes: bytes, mode: 0o644, range: { start: 0, end: bytes.length } }],
    request: { fingerprint: { tag: "article", id: "card-annual", classes: [], text: "Annual", parent: null, route: "/", viewport: { width: 1280, height: 720 } }, currentWidth: 320, width: 320 },
    plan: { relativePath: "style.css", range: { start: 0, end: bytes.length }, sourceIdentity: `seed:${index}`, route: "/", expectedHash: "seed", before: "", after: "", stylingMode: "vanilla-css", confidence: "exact", evidence: "Performance fixture", impact: { shared: false, locations: ["style.css"] }, allowedChangedFiles: ["style.css"] },
    preflight: { repository: { available: false, head: null, entries: [] }, beforeScreenshots: { page: { record: { status: "captured" }, bytes: png }, component: { record: { status: "captured" }, bytes: png } } }, verificationMs: 1,
  });
}

async function start(options: { capture?: ProjectProxyOptions["captureHistoryScreenshot"]; allow?: ProjectProxyOptions["allowHistoryScreenshot"]; prepare?: (root: string) => Promise<void>; realCapture?: boolean } = {}): Promise<string> {
  const base = path.join(projectRoot, ".reframe-test-artifacts", "phase10-e2e"); await mkdir(base, { recursive: true }); copyRoot = await mkdtemp(path.join(base, "vanilla-")); await cp(path.join(projectRoot, "demo", "vanilla-demo"), copyRoot, { recursive: true }); await rm(path.join(copyRoot, ".reframe"), { recursive: true, force: true }); await options.prepare?.(copyRoot);
  const port = await reservePort(); await port.release(); demo = await startViteDemo(copyRoot, port.port); captureBrowser = options.realCapture ? createBrowserScreenshotCapture(`http://127.0.0.1:${port.port}/`) : undefined; proxy = createProjectProxy(`http://127.0.0.1:${port.port}/`, { projectRoot: copyRoot, captureHistoryScreenshot: options.capture ?? captureBrowser?.capture ?? (async () => png), allowHistoryScreenshot: options.allow, historyScreenshotTimeoutMs: options.realCapture ? 15_000 : undefined, project: { id: "phase10_vanilla", name: "Phase 10 vanilla", framework: "vanilla", capabilities: { canExplore: true, canWriteSource: true } } }); return (await proxy.listen()).url;
}

async function ready(page: Page, url?: string): Promise<void> { if (url) await page.goto(url, { waitUntil: "domcontentloaded" }); await expect(page.locator("#reframe-root")).toHaveAttribute("data-reframe-state", "connected", { timeout: 10_000 }); }
async function apply(page: Page, width: number): Promise<void> {
  const beforeId = await page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.currentId); const selecting = await page.evaluate(() => window[Symbol.for("reframe.browser-client")].selectMode); if (!selecting) await page.locator('#reframe-root [data-reframe-tool="select"]').click(); await page.locator("#card-annual").click(); await expect(page.locator("#reframe-root [data-reframe-mapping]")).toHaveText("exact"); await page.evaluate((value) => window[Symbol.for("reframe.browser-client")].previewWidth(value), width); await page.locator("#reframe-root [data-reframe-apply]").click(); await expect(page.locator("#reframe-root [data-reframe-diagnostic]")).toContainText("source edit applied", { timeout: 15_000 }); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.currentId)).not.toBe(beforeId);
}
async function beginHold(page: Page): Promise<void> { const box = await page.locator("#reframe-root [data-reframe-time]").boundingBox(); if (!box) throw new Error("time control unavailable"); await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); }
async function endHold(page: Page): Promise<void> { await page.mouse.up(); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeHidden(); }

test.afterEach(async ({ page }) => { await page.mouse.up().catch(() => undefined); await proxy?.close(); proxy = undefined; await captureBrowser?.close(); captureBrowser = undefined; await demo?.stop(); demo = undefined; if (copyRoot) await rm(copyRoot, { recursive: true, force: true, maxRetries: 20, retryDelay: 50 }); copyRoot = undefined; });

test("P10-01 hold shows the exact previous screenshot and release returns to unchanged live page", async ({ page }) => {
  const url = await start({ realCapture: true }); await ready(page, url); await apply(page, 420); await apply(page, 430); const source = await readFile(path.join(copyRoot!, "style.css")); const route = page.url(); const live = await page.locator("#card-annual").evaluate((element) => element.outerHTML); await beginHold(page); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeVisible(); await expect(page.locator("#reframe-root [data-reframe-time-image]")).toHaveAttribute("src", /^blob:/); await expect(page.locator("#reframe-root [data-reframe-time-label]")).toContainText("Previous"); const imagePath = await page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.comparison.imagePath); expect(imagePath).toContain("/before/page"); expect(await page.evaluate((value) => fetch(value).then((response) => response.status), imagePath)).toBe(403); await endHold(page); expect(await readFile(path.join(copyRoot!, "style.css"))).toEqual(source); expect(page.url()).toBe(route); expect(await page.locator("#card-annual").evaluate((element) => element.outerHTML)).toBe(live);
});

test("P10-02 click opens deterministic history with route, viewport, files, prompt, and verification", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); await apply(page, 430); await page.locator("#reframe-root [data-reframe-time]").click(); const dialog = page.locator("#reframe-root [data-reframe-history-dialog]"); await expect(dialog).toBeVisible(); const items = dialog.locator(".history-item"); await expect(items).toHaveCount(2); await expect(items.first()).toContainText("Current"); await expect(items.first()).toContainText("/ · 1280×720 · passed"); await expect(items.first()).toContainText("style.css"); await expect(items.first()).toContainText("vanilla-css");
});

test("P10-03 history Restore Previous reuses the Phase 7 safety transaction", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); const prior = await readFile(path.join(copyRoot!, "style.css")); await apply(page, 430); await page.locator("#reframe-root [data-reframe-time]").click(); page.once("dialog", (dialog) => dialog.accept()); await page.locator("#reframe-root [data-reframe-history-dialog]", { has: page.locator("button", { hasText: "Restore Previous" }) }).locator("button", { hasText: "Restore Previous" }).click(); await expect.poll(() => readFile(path.join(copyRoot!, "style.css"))).toEqual(prior); await ready(page); const directories = (await readdir(path.join(copyRoot!, ".reframe", "history"), { withFileTypes: true })).filter((entry) => entry.isDirectory() && !entry.name.startsWith(".")); expect(directories.length).toBeGreaterThanOrEqual(3);
});

test("P10-04 another-route screenshot is clearly labeled and never presented as exact", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); await page.evaluate(() => history.pushState({}, "", "/another")); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.comparison?.exactRoute)).toBe(false); await beginHold(page); await expect(page.locator("#reframe-root [data-reframe-time-label]")).toContainText("route mismatch: / vs /another"); await endHold(page);
});

test("P10-05 viewport mismatch labels both dimensions and keeps the screenshot aspect-fit", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); await page.setViewportSize({ width: 900, height: 500 }); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.comparison?.exactViewport)).toBe(false); await beginHold(page); await expect(page.locator("#reframe-root [data-reframe-time-label]")).toContainText("1280×720 vs 900×500"); await expect(page.locator("#reframe-root [data-reframe-time-image]")).toHaveCSS("object-fit", "contain"); await endHold(page);
});

test("P10-06 missing, truncated, wrong-format, and hash-mismatched screenshots are unavailable", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); const id = await page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.currentId); const image = path.join(copyRoot!, ".reframe", "history", id, "before-page.png"); const original = await readFile(image); const cases: Array<Uint8Array | null> = [null, Buffer.from("truncated"), Buffer.from("GIF89a-wrong-format"), otherPng];
  for (const value of cases) { if (value) await writeFile(image, value); else await rm(image); await page.reload({ waitUntil: "domcontentloaded" }); await ready(page); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.checkpoints[0]?.valid)).toBe(false); await beginHold(page); await expect(page.locator("#reframe-root [data-reframe-time-label]")).toContainText("Previous unavailable"); await endHold(page); await page.locator("#reframe-root [data-reframe-time]").click(); await expect(page.locator("#reframe-root [data-reframe-history-dialog]")).toContainText("Unavailable/corrupt"); await page.locator("#reframe-root [data-reframe-history-close]").click(); await writeFile(image, original); }
});

test("P10-07 lost capture, pointer cancellation, hidden tab, and blur always reset hold state", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); for (const event of ["pointercancel", "lostpointercapture"] as const) { await beginHold(page); await page.locator("#reframe-root [data-reframe-time]").dispatchEvent(event, { pointerId: 1 }); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeHidden(); await page.mouse.up(); } const button = page.locator("#reframe-root [data-reframe-time]"); await button.dispatchEvent("pointerdown", { pointerId: 77, pointerType: "touch", isPrimary: true, button: 0 }); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeVisible(); await button.dispatchEvent("pointerup", { pointerId: 77, pointerType: "touch", isPrimary: true, button: 0 }); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeHidden(); await page.evaluate(() => window.dispatchEvent(new Event("blur"))); expect(await page.evaluate(() => window[Symbol.for("reframe.browser-client")].timeMachineState.holding)).toBe(false); await page.evaluate(() => document.dispatchEvent(new Event("visibilitychange"))); expect(await page.evaluate(() => window[Symbol.for("reframe.browser-client")].timeMachineState.overlayVisible)).toBe(false);
});

test("P10-08 reload while comparing removes the old overlay/listeners and remounts current state", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); await beginHold(page); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeVisible(); await page.reload({ waitUntil: "domcontentloaded" }); await ready(page); await expect(page.locator("#reframe-root")).toHaveCount(1); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeHidden(); await beginHold(page); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeVisible(); await endHold(page);
});

test("P10-09 component-only privacy never fetches or displays an unmasked page alternative", async ({ page }) => {
  const url = await start({ allow: (_stage, _context, kind) => kind === "component" }); await ready(page, url); await apply(page, 420); await beginHold(page); await expect(page.locator("#reframe-root [data-reframe-time-label]")).toContainText("PRIVACY_EXCLUDED"); await expect(page.locator("#reframe-root [data-reframe-time-image]")).not.toHaveAttribute("src", /.+/); await endHold(page); const id = await page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.currentId); const files = await readdir(path.join(copyRoot!, ".reframe", "history", id)); expect(files.some((name) => name.includes("component.png"))).toBe(true); expect(files.some((name) => name.includes("page.png"))).toBe(false);
});

test("P10-10 one hundred comparisons perform no source, Git-history, process, route, or live DOM mutation", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); const sourceFile = path.join(copyRoot!, "style.css"); const beforeSource = await readFile(sourceFile); const beforeMtime = (await stat(sourceFile)).mtimeMs; const historyRoot = path.join(copyRoot!, ".reframe", "history"); const beforeHistory = (await readdir(historyRoot)).sort(); const pid = demo!.pid; const route = page.url(); const live = await page.locator("#card-annual").evaluate((element) => element.outerHTML); await page.evaluate(async () => { const api = window[Symbol.for("reframe.browser-client")]; for (let index = 0; index < 100; index += 1) { await api.showPrevious(); api.hidePrevious(); } }); expect(await readFile(sourceFile)).toEqual(beforeSource); expect((await stat(sourceFile)).mtimeMs).toBe(beforeMtime); expect((await readdir(historyRoot)).sort()).toEqual(beforeHistory); expect(demo!.pid).toBe(pid); expect(page.url()).toBe(route); expect(await page.locator("#card-annual").evaluate((element) => element.outerHTML)).toBe(live);
});

test("P10-11 keyboard operation announces state, Escape closes, and focus returns to trigger", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); const button = page.getByRole("button", { name: "Hold to view previous" }); await button.focus(); await page.keyboard.down("Space"); await expect(page.getByRole("img", { name: "Previous design comparison" })).toBeVisible(); await page.keyboard.press("Escape"); await expect(page.getByRole("img", { name: "Previous design comparison" })).toBeHidden(); await page.keyboard.up("Space"); await button.press("Enter"); const dialog = page.getByRole("dialog", { name: "Visual history" }); await expect(dialog).toBeVisible(); await expect(page.getByRole("button", { name: "Close visual history" })).toBeFocused(); await page.keyboard.press("Escape"); await expect(dialog).toBeHidden(); await expect(button).toBeFocused();
});

test("P10-12 comparison refreshes after scroll, navigation, restore, and a new checkpoint without duplicates", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); await apply(page, 430); const firstPath = await page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.comparison.imagePath); await page.evaluate(() => scrollTo(0, document.body.scrollHeight)); await page.evaluate(() => history.pushState({}, "", "/other")); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.comparison?.exactRoute)).toBe(false); await page.evaluate(() => history.pushState({}, "", "/")); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.comparison?.exactRoute)).toBe(true); page.once("dialog", (dialog) => dialog.accept()); const reloaded = page.waitForEvent("load"); await page.locator("#reframe-root [data-reframe-restore]").click(); await reloaded; await ready(page); await apply(page, 440); const nextPath = await page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.comparison.imagePath); expect(nextPath).not.toBe(firstPath); await expect(page.locator("#reframe-root")).toHaveCount(1);
});

test("P10-13 pointer, keyboard, blur cancellation, and history are equivalent across browsers", async ({ page }) => {
  const url = await start(); await ready(page, url); await apply(page, 420); await beginHold(page); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeVisible(); await endHold(page); const button = page.getByRole("button", { name: "Hold to view previous" }); await button.focus(); await page.keyboard.down("Space"); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeVisible(); await page.evaluate(() => window.dispatchEvent(new Event("blur"))); await expect(page.locator("#reframe-root [data-reframe-time-overlay]")).toBeHidden(); await page.keyboard.up("Space"); await button.press("Enter"); await expect(page.getByRole("dialog", { name: "Visual history" })).toBeVisible();
});

test("P10-14 preloaded hold p95 is at most 150ms, 100-item list render at most 500ms, and cache stays bounded", async ({ page }) => {
  const url = await start({ prepare: (root) => seedHistory(root, 100) }); await ready(page, url); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].historyState.checkpoints.length)).toBe(100); await expect.poll(() => page.evaluate(() => window[Symbol.for("reframe.browser-client")].timeMachineState.cacheSize)).toBeGreaterThan(0); await page.evaluate(async () => { const api = window[Symbol.for("reframe.browser-client")]; for (let index = 0; index < 50; index += 1) { await api.showPrevious(); api.hidePrevious(); } }); await page.locator("#reframe-root [data-reframe-time]").click(); await expect(page.locator("#reframe-root .history-item")).toHaveCount(100); const metrics = await page.evaluate(() => ({ metrics: window[Symbol.for("reframe.browser-client")].performanceMetrics, cache: window[Symbol.for("reframe.browser-client")].timeMachineState.cacheSize })); const sorted = [...metrics.metrics.timeMachine].sort((a, b) => a - b); const p95 = sorted[Math.ceil(sorted.length * .95) - 1]; const list = metrics.metrics.historyList.at(-1); console.log("P10-14", JSON.stringify({ samples: sorted.length, p95, list, cache: metrics.cache })); expect(p95).toBeLessThanOrEqual(150); expect(list).toBeLessThanOrEqual(500); expect(metrics.cache).toBeLessThanOrEqual(3);
});
