import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, readdir, rename, rm, symlink, writeFile } from "node:fs/promises";
import { open } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createAnnotationStore, type AnnotationDraft } from "../../packages/dev-server/src/annotations.js";

const ids = Array.from({ length: 30 }, (_, index) => `00000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`);
let root = ""; let nextId = 0;
const source = '<article class="card annual"><h2>Annual</h2><p>The official edit target.</p></article>\n';
const fingerprint = { tag: "article", id: null, classes: ["card", "annual"], text: "Annual The official edit target.", parent: { tag: "main", id: null, classes: ["cards"] }, route: "/", viewport: { width: 1280, height: 720 } } as const;
const store = (options = {}) => createAnnotationStore(root, { createId: () => ids[nextId++]!, ...options });
const draft = (overrides: Partial<AnnotationDraft> = {}): AnnotationDraft => ({ author: "Local reviewer", component: "AnnualCard", fingerprint, source: { path: "index.html", line: 1, evidence: "exact source metadata" }, route: "/", viewport: { width: 1280, height: 720 }, comment: "Increase the visual emphasis.", highlight: { x: 0.1, y: 0.1, width: 0.8, height: 0.8 }, relatedCheckpoint: "checkpoint-current", relatedDesignDna: "dna-current", anchorConfidence: "exact", ...overrides });
const git = (cwd: string, ...args: string[]) => execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });

beforeEach(async () => { nextId = 0; root = await mkdtemp(path.join(os.tmpdir(), "reframe-phase11-")); await writeFile(path.join(root, "index.html"), source); });
afterEach(async () => { await rm(root, { recursive: true, force: true }); });

describe("Phase 11 annotation store", () => {
  it("P11-03 loads a Git-pulled annotation through the filesystem watcher without Reframe synchronization", async () => {
    const workspace = root; const remote = path.join(workspace, "remote.git"); const cloneA = path.join(workspace, "clone-a"); const cloneB = path.join(workspace, "clone-b"); await rm(path.join(workspace, "index.html"));
    git(workspace, "init", "--bare", remote); git(workspace, "clone", remote, cloneA); git(cloneA, "config", "user.email", "reframe@example.test"); git(cloneA, "config", "user.name", "Reframe Test"); await writeFile(path.join(cloneA, "index.html"), source); await mkdir(path.join(cloneA, ".reframe")); await writeFile(path.join(cloneA, ".reframe", ".gitignore"), "*\n"); git(cloneA, "add", "index.html"); git(cloneA, "commit", "-m", "source"); git(cloneA, "push", "origin", "HEAD:main"); git(workspace, "clone", "--branch", "main", remote, cloneB);
    const a = createAnnotationStore(cloneA, { createId: () => ids[0]! }); await a.create(draft()); expect(await readFile(path.join(cloneA, ".reframe", ".gitignore"), "utf8")).toBe("history/\n.gitignore\n"); git(cloneA, "add", ".reframe/annotations"); git(cloneA, "commit", "-m", "annotation"); git(cloneA, "push", "origin", "HEAD:main");
    const b = createAnnotationStore(cloneB, { watcherDebounceMs: 20 }); let seen = 0; let resolveLoaded!: () => void; const loaded = new Promise<void>((resolve) => { resolveLoaded = resolve; }); let stop = () => {}; stop = await b.subscribe((state) => { if (state.annotations.some((item) => item.annotation?.id === ids[0])) { seen += 1; stop(); resolveLoaded(); } }); git(cloneB, "pull", "--ff-only"); await Promise.race([loaded, new Promise((_, reject) => setTimeout(() => reject(new Error("WATCH_TIMEOUT")), 2_000))]); expect(seen).toBe(1); expect((await b.load({ route: "/" })).annotations[0]?.resolution).toBe("exact"); await Promise.all([a.close(), b.close()]);
  });

  it("P11-04 relocates a moved source anchor only from unique source-line evidence", async () => { const annotations = store(); const created = await annotations.create(draft()); await rename(path.join(root, "index.html"), path.join(root, "moved.html")); const view = (await annotations.load()).annotations.find((item) => item.annotation?.id === created.id)!; expect(view.resolution).toBe("relocated"); expect(view.resolvedSource).toMatchObject({ path: "moved.html", line: 1 }); expect(view.resolvedSource?.evidence).toContain("unique source-line hash"); });

  it("P11-05 preserves deleted and indistinguishable anchors as orphaned or ambiguous", async () => { const annotations = store(); const first = await annotations.create(draft()); await rm(path.join(root, "index.html")); expect((await annotations.load()).annotations.find((item) => item.annotation?.id === first.id)?.resolution).toBe("orphaned"); await writeFile(path.join(root, "a.html"), source); await writeFile(path.join(root, "b.html"), source); expect((await annotations.load()).annotations.find((item) => item.annotation?.id === first.id)?.resolution).toBe("ambiguous"); expect((await annotations.load()).annotations.find((item) => item.annotation?.id === first.id)?.resolvedSource).toBeNull(); });

  it("P11-06 isolates malformed, conflicted, wrong-schema, and unsupported files while valid files load", async () => { const annotations = store(); const valid = await annotations.create(draft()); const folder = path.join(root, ".reframe", "annotations"); await writeFile(path.join(folder, `${ids[1]}.json`), "{"); await writeFile(path.join(folder, `${ids[2]}.json`), "<<<<<<< ours\n{}\n=======\n{}\n>>>>>>> theirs\n"); await writeFile(path.join(folder, `${ids[3]}.json`), JSON.stringify({ schemaVersion: 1, id: 2 })); await writeFile(path.join(folder, `${ids[4]}.json`), JSON.stringify({ ...(JSON.parse(await readFile(path.join(folder, `${valid.id}.json`), "utf8"))), id: ids[4], schemaVersion: 99 })); const state = await annotations.load(); expect(state.annotations.some((item) => item.annotation?.id === valid.id)).toBe(true); expect(state.issues.map((item) => item.error)).toEqual(expect.arrayContaining(["ANNOTATION_GIT_CONFLICT", "ANNOTATION_SCHEMA_INVALID", "ANNOTATION_VERSION_UNSUPPORTED"])); expect(await readdir(folder)).toHaveLength(5); });

  it("P11-07 surfaces duplicate IDs with both filenames and overwrites neither", async () => { const annotations = store(); const first = await annotations.create(draft()); const folder = path.join(root, ".reframe", "annotations"); const secondFile = `${ids[1]}.json`; await writeFile(path.join(folder, secondFile), await readFile(path.join(folder, `${first.id}.json`))); const state = await annotations.load(); const conflicts = state.issues.filter((item) => item.error?.startsWith("ANNOTATION_ID_DUPLICATE")); expect(conflicts).toHaveLength(2); expect(conflicts.every((item) => item.error?.includes(`${first.id}.json`) && item.error.includes(secondFile))).toBe(true); });

  it("P11-08 rejects executable markup, unsafe protocols, and huge comments while plain text remains literal", async () => { const annotations = store(); for (const comment of ["<script>globalThis.pwned=1</script>", '<img src=x onerror="globalThis.pwned=1">', "[click](javascript:alert(1))"]) await expect(annotations.create(draft({ comment }))).rejects.toThrow("ANNOTATION_COMMENT_UNSAFE"); await expect(annotations.create(draft({ comment: "x".repeat(4_097) }))).rejects.toThrow("ANNOTATION_COMMENT_TOO_LONG"); const safe = await annotations.create(draft({ comment: "Use <strong>literal text</strong>." })); expect(safe.comment).toBe("Use <strong>literal text</strong>."); });

  it("P11-09 rejects traversal, absolute, symlink-escape, and Windows device source paths before access", async () => { const annotations = store(); for (const sourcePath of ["../outside.html", "C:/outside.html", "/outside.html", "con/file.html", "folder\\file.html"]) await expect(annotations.create(draft({ source: { path: sourcePath, line: 1, evidence: "bad" } }))).rejects.toThrow(/ANNOTATION_(DRAFT|SOURCE_PATH)_INVALID/); const outside = await mkdtemp(path.join(os.tmpdir(), "reframe-phase11-outside-")); await writeFile(path.join(outside, "outside.html"), source); await symlink(outside, path.join(root, "escape"), "junction"); await expect(annotations.create(draft({ source: { path: "escape/outside.html", line: 1, evidence: "bad" } }))).rejects.toThrow("ANNOTATION_SOURCE_PATH_ESCAPE"); await rm(outside, { recursive: true, force: true }); });

  it("P11-10 cleans failed atomic writes and leaves application source/history unchanged", async () => { const before = await readFile(path.join(root, "index.html")); const failing = store({ operations: { link: (async () => { const error = new Error("disk full"); Object.assign(error, { code: "ENOSPC" }); throw error; }) as never } }); await expect(failing.create(draft())).rejects.toThrow("disk full"); const folder = path.join(root, ".reframe", "annotations"); expect((await readdir(folder)).filter((name) => name.endsWith(".json") || name.endsWith(".tmp"))).toEqual([]); expect(await readFile(path.join(root, "index.html"))).toEqual(before); await expect(readFile(path.join(root, ".reframe", "history", "current.json"))).rejects.toThrow(); const retry = store(); await expect(retry.create(draft())).resolves.toMatchObject({ status: "open" }); });

  it("P11-11 keeps simultaneous creates and independent updates in separate files and coalesces watcher state", async () => { const annotations = store({ watcherDebounceMs: 20 }); const [a, b] = await Promise.all([annotations.create(draft({ comment: "A" })), annotations.create(draft({ comment: "B" }))]); expect(a.id).not.toBe(b.id); let calls = 0; let resolveLoaded!: () => void; const loaded = new Promise<void>((resolve) => { resolveLoaded = resolve; }); let stop = () => {}; stop = await annotations.subscribe((state) => { calls += 1; if (state.annotations.length === 2 && state.annotations.every((item) => item.annotation?.status === "resolved")) { stop(); resolveLoaded(); } }); await Promise.all([annotations.update(a.id, "resolve"), annotations.update(b.id, "resolve")]); await Promise.race([loaded, new Promise((_, reject) => setTimeout(() => reject(new Error("WATCH_TIMEOUT")), 2_000))]); expect(calls).toBe(1); expect((await readdir(path.join(root, ".reframe", "annotations"))).filter((name) => name.endsWith(".json"))).toHaveLength(2); });

  it("P11-12 preserves a same-file Git conflict verbatim and never auto-resolves it", async () => { const annotations = store(); const created = await annotations.create(draft()); const file = path.join(root, ".reframe", "annotations", `${created.id}.json`); const conflicted = "<<<<<<< ours\n{\"comment\":\"ours\"}\n=======\n{\"comment\":\"theirs\"}\n>>>>>>> theirs\n"; await writeFile(file, conflicted); const state = await annotations.load(); expect(state.issues[0]).toMatchObject({ file: `${created.id}.json`, error: "ANNOTATION_GIT_CONFLICT" }); expect(await readFile(file, "utf8")).toBe(conflicted); });

  it("P11-13 filters checkpoint relationships without changing current source", async () => { const annotations = store(); const before = await readFile(path.join(root, "index.html")); const current = await annotations.create(draft({ relatedCheckpoint: "current" })); const old = await annotations.create(draft({ relatedCheckpoint: "old" })); const state = await annotations.load({ route: "/", checkpointId: "old" }); expect(state.annotations.find((item) => item.annotation?.id === old.id)?.checkpointRelationship).toBe("related"); expect(state.annotations.find((item) => item.annotation?.id === current.id)?.checkpointRelationship).toBe("other"); expect(state.renderedForRoute).toBe(1); expect(await readFile(path.join(root, "index.html"))).toEqual(before); });

  it("P11-14 requires explicit promotion confirmation and creates a scoped proposal without rewriting Design DNA", async () => { const annotations = store(); const created = await annotations.create(draft()); const dna = path.join(root, ".reframe", "design-dna"); await mkdir(dna, { recursive: true }); const tokens = '{"schemaVersion":1,"unchanged":true}\n'; await writeFile(path.join(dna, "tokens.json"), tokens); await expect(annotations.promote(created.id, false)).rejects.toThrow("DESIGN_DNA_CONFIRMATION_REQUIRED"); const proposal = await annotations.promote(created.id, true); expect(proposal).toMatchObject({ annotationId: created.id, status: "needs-review", scope: { component: "AnnualCard", sourcePath: "index.html", route: "/" } }); expect(await readFile(path.join(dna, "tokens.json"), "utf8")).toBe(tokens); expect(JSON.parse(await readFile(path.join(dna, "proposals", `${proposal.id}.json`), "utf8"))).toEqual(proposal); });

  it("P11-16 preserves portable UTF-8 JSON, forward-slash source paths, IDs, and timestamps on Windows", async () => { await mkdir(path.join(root, "src", "组件"), { recursive: true }); await writeFile(path.join(root, "src", "组件", "卡片.html"), source); const annotations = store({ now: () => "2026-07-17T13:00:00.000Z" }); const created = await annotations.create(draft({ author: "设计者", comment: "保持品牌一致。", component: "年度卡片", source: { path: "src/组件/卡片.html", line: 1, evidence: "portable source" } })); const bytes = await readFile(path.join(root, ".reframe", "annotations", `${created.id}.json`)); const saved = JSON.parse(bytes.toString("utf8")); expect(saved).toMatchObject({ id: created.id, author: "设计者", comment: "保持品牌一致。", createdAt: "2026-07-17T13:00:00.000Z", source: { path: "src/组件/卡片.html" } }); expect(bytes.includes(Buffer.from("\r\n"))).toBe(false); expect((await annotations.load()).annotations[0]?.resolution).toBe("exact"); });

  it("P11-18 saves pasted image annotations with binary payload and reloads them on the route", async () => {
    const annotations = store();
    const id = "20000000-0000-4000-8000-000000000001";
    const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
    const imagePath = await annotations.saveImage(id, png);
    const created = await annotations.createImage({ id, route: "/", viewport: { width: 1280, height: 720 }, position: { x: 120, y: 140, width: 240, height: 180 }, imagePath });
    expect(created).toMatchObject({ kind: "image", route: "/", status: "open", imagePath, position: { x: 120, y: 140, width: 240, height: 180 } });
    expect(await readFile(path.join(root, ".reframe", imagePath))).toEqual(png);
    const loaded = await annotations.load({ route: "/" });
    expect(loaded.annotations).toHaveLength(1);
    expect(loaded.annotations[0]?.annotation).toMatchObject({ id, kind: "image", imagePath });
    expect(loaded.annotations[0]?.resolution).toBe("exact");
  });
});
