import type { ElementFingerprint } from "@reframe/shared";
import { createHash, randomUUID } from "node:crypto";
import { watch, type FSWatcher } from "node:fs";
import { link, lstat, mkdir, open, readFile, readdir, realpath, rename, rm, unlink } from "node:fs/promises";
import path from "node:path";

const schemaVersion = 1 as const; const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; const hashPattern = /^[0-9a-f]{64}$/; const unsafeComment = /<\/?(?:script|iframe|object|embed|svg|math)\b|\bon\w+\s*=|\]\(\s*(?:javascript|data|file):/i; const deviceName = /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i;
const sourceExtensions = /\.(?:css|html?|jsx?|tsx?|vue|svelte)$/i; const ignoredDirectories = new Set([".git", ".reframe", "node_modules", "dist", "build", "coverage", "test-results"]);
const sha256 = (value: string | Uint8Array) => createHash("sha256").update(value).digest("hex"); const normalize = (value: string) => value.replaceAll("\\", "/");
const inside = (root: string, target: string) => { const relative = path.relative(root, target); return relative === "" || (relative !== ".." && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative)); };

export type AnnotationStatus = "open" | "resolved";
export type AnnotationResolution = "exact" | "relocated" | "orphaned" | "ambiguous" | "conflict";
export interface AnnotationSource { readonly path: string; readonly line: number; readonly endLine: number; readonly snippet: string; readonly hash: string; readonly evidence: string }
export interface AnnotationHighlight { readonly x: number; readonly y: number; readonly width: number; readonly height: number }
export interface AnnotationHistory { readonly action: "created" | "resolved" | "reopened"; readonly at: string }
export type AnnotationKind = "comment" | "image";
export interface AnnotationPosition { readonly x: number; readonly y: number; readonly width?: number; readonly height?: number }
export interface Annotation {
  readonly schemaVersion: typeof schemaVersion; readonly id: string; readonly kind: AnnotationKind; readonly author: string; readonly createdAt: string; readonly updatedAt: string; readonly component: string; readonly fingerprint: ElementFingerprint; readonly source: AnnotationSource; readonly route: string; readonly viewport: { readonly width: number; readonly height: number }; readonly comment: string; readonly replies: readonly []; readonly highlight: AnnotationHighlight | null; readonly imagePath: string | null; readonly position: AnnotationPosition | null; readonly status: AnnotationStatus; readonly relatedCheckpoint: string | null; readonly relatedDesignDna: string | null; readonly anchorConfidence: "exact" | "probable"; readonly history: readonly AnnotationHistory[];
}
export interface ImageAnnotationDraft { readonly id?: string; readonly route: string; readonly viewport: { readonly width: number; readonly height: number }; readonly position: AnnotationPosition; readonly imagePath: string; readonly author?: string }
export interface AnnotationDraft { readonly author: string; readonly component: string; readonly fingerprint: ElementFingerprint; readonly source: { readonly path: string; readonly line: number; readonly endLine?: number; readonly evidence: string }; readonly route: string; readonly viewport: { readonly width: number; readonly height: number }; readonly comment: string; readonly highlight?: AnnotationHighlight | null; readonly relatedCheckpoint?: string | null; readonly relatedDesignDna?: string | null; readonly anchorConfidence: "exact" | "probable" }
export interface AnnotationView { readonly file: string; readonly annotation: Annotation | null; readonly resolution: AnnotationResolution | "invalid" | "unsupported"; readonly resolvedSource: AnnotationSource | null; readonly checkpointRelationship: "current" | "related" | "other"; readonly error?: string }
export interface AnnotationState { readonly annotations: readonly AnnotationView[]; readonly issues: readonly AnnotationView[]; readonly parsedFiles: number; readonly renderedForRoute: number }
export interface DesignDnaProposal { readonly schemaVersion: 1; readonly id: string; readonly annotationId: string; readonly createdAt: string; readonly status: "needs-review"; readonly rule: string; readonly scope: { readonly component: string; readonly sourcePath: string; readonly route: string } }
export interface AnnotationStoreOptions { readonly createId?: () => string; readonly now?: () => string; readonly watcherDebounceMs?: number; readonly operations?: Partial<{ mkdir: typeof mkdir; readFile: typeof readFile; readdir: typeof readdir; realpath: typeof realpath; rename: typeof rename; rm: typeof rm; lstat: typeof lstat; link: typeof link; unlink: typeof unlink; open: typeof open }> }

function object(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === "object" && !Array.isArray(value); }
function exact(value: Record<string, unknown>, keys: readonly string[]): boolean { const actual = Object.keys(value).sort(); const expected = [...keys].sort(); return actual.length === expected.length && actual.every((key, index) => key === expected[index]); }
function text(value: unknown, max: number): value is string { return typeof value === "string" && value.length > 0 && value.length <= max && !value.includes("\0"); }
function integer(value: unknown, max = Number.MAX_SAFE_INTEGER): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 0 && value <= max; }
function finite(value: unknown): value is number { return typeof value === "number" && Number.isFinite(value) && Math.abs(value) <= 1_000_000; }
function route(value: unknown): value is string { return typeof value === "string" && value.startsWith("/") && value.length <= 2_048 && !value.includes("\\") && !value.includes("\0") && !value.split(/[/?#]/).includes(".."); }
function relativePath(value: unknown): value is string { if (typeof value !== "string" || !value || value.length > 2_048 || value.includes("\\") || value.includes("\0") || path.isAbsolute(value) || path.win32.isAbsolute(value)) return false; const parts = value.split("/"); return parts.every((part) => part && part !== "." && part !== ".." && !deviceName.test(part)); }
function viewport(value: unknown): value is { width: number; height: number } { return object(value) && exact(value, ["width", "height"]) && integer(value.width, 100_000) && integer(value.height, 100_000) && value.width > 0 && value.height > 0; }
function highlight(value: unknown): value is AnnotationHighlight | null { return value === null || (object(value) && exact(value, ["x", "y", "width", "height"]) && finite(value.x) && finite(value.y) && finite(value.width) && finite(value.height) && value.width > 0 && value.height > 0); }
function fingerprint(value: unknown): value is ElementFingerprint { return object(value) && exact(value, ["tag", "id", "classes", "text", "parent", "route", "viewport"]) && text(value.tag, 32) && (value.id === null || text(value.id, 128)) && Array.isArray(value.classes) && value.classes.length <= 16 && value.classes.every((item) => text(item, 128)) && typeof value.text === "string" && value.text.length <= 256 && (value.parent === null || (object(value.parent) && exact(value.parent, ["tag", "id", "classes"]) && text(value.parent.tag, 32) && (value.parent.id === null || text(value.parent.id, 128)) && Array.isArray(value.parent.classes) && value.parent.classes.every((item) => text(item, 128)))) && route(value.route) && viewport(value.viewport); }
function source(value: unknown): value is AnnotationSource { return object(value) && exact(value, ["path", "line", "endLine", "snippet", "hash", "evidence"]) && relativePath(value.path) && integer(value.line, 10_000_000) && value.line > 0 && integer(value.endLine, 10_000_000) && value.endLine >= value.line && text(value.snippet, 1_024) && typeof value.hash === "string" && hashPattern.test(value.hash) && text(value.evidence, 1_024); }
function history(value: unknown): value is AnnotationHistory[] { return Array.isArray(value) && value.length <= 256 && value.every((item) => object(item) && exact(item, ["action", "at"]) && ["created", "resolved", "reopened"].includes(String(item.action)) && !Number.isNaN(Date.parse(String(item.at)))); }
function position(value: unknown): value is AnnotationPosition { if (!object(value) || !finite(value.x) || !finite(value.y)) return false; if (value.width !== undefined && (!finite(value.width) || value.width <= 0)) return false; if (value.height !== undefined && (!finite(value.height) || value.height <= 0)) return false; return Object.keys(value).every((key) => ["x", "y", "width", "height"].includes(key)); }
function normalizeAnnotationRecord(value: Record<string, unknown>): Record<string, unknown> { const next = { ...value }; if (next.kind === undefined) next.kind = "comment"; if (next.imagePath === undefined) next.imagePath = null; if (next.position === undefined) next.position = null; if (next.kind === "image" && next.position && typeof next.position === "object" && next.position !== null) { const pos = { ...(next.position as Record<string, unknown>) }; if (pos.width === undefined) pos.width = 360; if (pos.height === undefined) pos.height = 270; next.position = pos; } return next; }
function validateAnnotation(value: unknown): Annotation { if (!object(value)) throw new Error("ANNOTATION_SCHEMA_INVALID"); const normalized = normalizeAnnotationRecord(value); const keys = ["schemaVersion", "id", "kind", "author", "createdAt", "updatedAt", "component", "fingerprint", "source", "route", "viewport", "comment", "replies", "highlight", "imagePath", "position", "status", "relatedCheckpoint", "relatedDesignDna", "anchorConfidence", "history"]; if (!exact(normalized, keys)) throw new Error("ANNOTATION_SCHEMA_INVALID"); if (normalized.schemaVersion !== schemaVersion) throw new Error("ANNOTATION_VERSION_UNSUPPORTED"); const kind = String(normalized.kind); if (!["comment", "image"].includes(kind)) throw new Error("ANNOTATION_SCHEMA_INVALID"); if (!uuidPattern.test(String(normalized.id)) || !text(normalized.author, 128) || Number.isNaN(Date.parse(String(normalized.createdAt))) || Number.isNaN(Date.parse(String(normalized.updatedAt))) || !text(normalized.component, 256) || !fingerprint(normalized.fingerprint) || !source(normalized.source) || !route(normalized.route) || !viewport(normalized.viewport) || typeof normalized.comment !== "string" || normalized.comment.length > 4_096 || (kind === "comment" && (!normalized.comment || unsafeComment.test(normalized.comment))) || !Array.isArray(normalized.replies) || normalized.replies.length !== 0 || !highlight(normalized.highlight) || (normalized.imagePath !== null && (typeof normalized.imagePath !== "string" || !relativePath(normalized.imagePath))) || (normalized.position !== null && !position(normalized.position)) || (kind === "image" && (!normalized.imagePath || !position(normalized.position))) || !["open", "resolved"].includes(String(normalized.status)) || (normalized.relatedCheckpoint !== null && !text(normalized.relatedCheckpoint, 128)) || (normalized.relatedDesignDna !== null && !text(normalized.relatedDesignDna, 128)) || !["exact", "probable"].includes(String(normalized.anchorConfidence)) || !history(normalized.history)) throw new Error("ANNOTATION_SCHEMA_INVALID"); return normalized as unknown as Annotation; }
function validateDraft(value: AnnotationDraft): void { if (!object(value) || !text(value.author, 128) || !text(value.component, 256) || !fingerprint(value.fingerprint) || !relativePath(value.source?.path) || !integer(value.source?.line, 10_000_000) || value.source.line < 1 || !text(value.source?.evidence, 1_024) || !route(value.route) || !viewport(value.viewport) || !text(value.comment, 4_096) || !highlight(value.highlight ?? null) || !["exact", "probable"].includes(value.anchorConfidence)) throw new Error(value.comment?.length > 4_096 ? "ANNOTATION_COMMENT_TOO_LONG" : "ANNOTATION_DRAFT_INVALID"); if (unsafeComment.test(value.comment)) throw new Error("ANNOTATION_COMMENT_UNSAFE"); }

export function createAnnotationStore(projectRoot: string, options: AnnotationStoreOptions = {}) {
  const ops = { mkdir, readFile, readdir, realpath, rename, rm, lstat, link, unlink, open, ...options.operations }; const annotationDirectory = path.join(projectRoot, ".reframe", "annotations"); const watchers = new Set<FSWatcher>(); let rootPromise: Promise<string> | undefined; let directoryPromise: Promise<string> | undefined;
  const project = () => rootPromise ??= ops.realpath(projectRoot);
  const migrateLegacyIgnore = async (root: string) => { const file = path.join(root, ".reframe", ".gitignore"); const current = await ops.readFile(file, "utf8").catch(() => null); if (current === null) return; const trimmed = String(current).trim(); if (trimmed === "*") { const temporary = `${file}.${randomUUID()}.tmp`; try { const handle = await ops.open(temporary, "wx"); try { await handle.writeFile("history/\n.gitignore\n", "utf8"); await handle.sync(); } finally { await handle.close(); } await ops.rename(temporary, file); } finally { await ops.rm(temporary, { force: true }).catch(() => undefined); } return; } if (current.includes("*") && !current.includes("!annotations/")) await atomicReplace(file, `${current.endsWith("\n") ? current : current + "\n"}!annotations/\n!annotations/**\n`); };
  const directory = async () => { if (!directoryPromise) directoryPromise = (async () => { const root = await project(); await ops.mkdir(annotationDirectory, { recursive: true }); await migrateLegacyIgnore(root); const resolved = await ops.realpath(annotationDirectory); if (!inside(root, resolved)) throw new Error("ANNOTATION_PATH_ESCAPE"); return resolved; })(); return directoryPromise; };
  const safeSource = async (relative: string) => { if (!relativePath(relative)) throw new Error("ANNOTATION_SOURCE_PATH_INVALID"); const root = await project(); const absolute = path.resolve(root, ...relative.split("/")); if (!inside(root, absolute)) throw new Error("ANNOTATION_SOURCE_PATH_INVALID"); const resolved = await ops.realpath(absolute).catch(() => null); if (!resolved || !inside(root, resolved) || !(await ops.lstat(resolved)).isFile()) throw new Error(resolved && !inside(root, resolved) ? "ANNOTATION_SOURCE_PATH_ESCAPE" : "ANNOTATION_SOURCE_UNAVAILABLE"); return { root, absolute: resolved }; };
  const durable = async (file: string, contents: string) => { const handle = await ops.open(file, "wx"); try { await handle.writeFile(contents, "utf8"); await handle.sync(); } finally { await handle.close(); } };
  const atomicFolder = async (file: string) => { const root = await project(); const folder = await ops.realpath(path.dirname(file)); if (!inside(root, folder)) throw new Error("ANNOTATION_PATH_ESCAPE"); return folder; };
  const atomicCreate = async (file: string, contents: string) => { const folder = await atomicFolder(file); const temporary = path.join(folder, `.${path.basename(file)}.${randomUUID()}.tmp`); try { await durable(temporary, contents); await ops.link(temporary, file); } finally { await ops.unlink(temporary).catch(() => undefined); } };
  const atomicReplace = async (file: string, contents: string) => { const folder = await atomicFolder(file); const temporary = path.join(folder, `.${path.basename(file)}.${randomUUID()}.tmp`); try { await durable(temporary, contents); await ops.rename(temporary, file); } finally { await ops.rm(temporary, { force: true }).catch(() => undefined); } };
  const annotationFile = async (id: string) => { if (!uuidPattern.test(id)) throw new Error("ANNOTATION_ID_INVALID"); return path.join(await directory(), `${id.toLowerCase()}.json`); };
  const sourceLines = async (relative: string, cache?: Map<string, string[]>) => { const key = normalize(relative); const cached = cache?.get(key); if (cached) return cached; const { absolute } = await safeSource(key); const lines = String(await ops.readFile(absolute, "utf8")).split(/\r?\n/); cache?.set(key, lines); return lines; };
  const snippetAt = async (relative: string, line: number, cache?: Map<string, string[]>) => { const lines = await sourceLines(relative, cache); const snippet = lines[line - 1]?.trim(); if (!snippet) throw new Error("ANNOTATION_SOURCE_LINE_INVALID"); return { path: normalize(relative), line, endLine: line, snippet: snippet.slice(0, 1_024), hash: sha256(snippet.slice(0, 1_024)) }; };
  const sourceFiles = async () => { const root = await project(); const files: string[] = []; const queue = [root]; while (queue.length) { const current = queue.shift()!; for (const entry of await ops.readdir(current, { withFileTypes: true })) { if (ignoredDirectories.has(entry.name)) continue; const absolute = path.join(current, entry.name); if (entry.isDirectory()) queue.push(absolute); else if (entry.isFile() && sourceExtensions.test(entry.name)) files.push(normalize(path.relative(root, absolute))); } } return files; };
  const resolve = async (annotation: Annotation, lines: Map<string, string[]>, moved: { index?: Map<string, Array<{ path: string; line: number; snippet: string }>> }): Promise<{ resolution: AnnotationResolution; source: AnnotationSource | null }> => { if (annotation.kind === "image") return { resolution: "exact", source: annotation.source }; try { const current = await snippetAt(annotation.source.path, annotation.source.line, lines); if (current.hash === annotation.source.hash) return { resolution: "exact", source: annotation.source }; return { resolution: "relocated", source: { ...current, evidence: `Source path and line retained after content edit at ${annotation.source.path}:${annotation.source.line}` } }; } catch { /* search moved source below */ } if (!moved.index) { moved.index = new Map(); for (const file of await sourceFiles()) { let contents: string[]; try { contents = await sourceLines(file, lines); } catch { continue; } for (let index = 0; index < contents.length; index += 1) { const snippet = contents[index]!.trim().slice(0, 1_024); if (!snippet) continue; const key = sha256(snippet); const matches = moved.index.get(key) ?? []; if (matches.length < 2) matches.push({ path: file, line: index + 1, snippet }); moved.index.set(key, matches); } } } const matches = moved.index.get(annotation.source.hash) ?? []; if (matches.length !== 1) return { resolution: matches.length ? "ambiguous" : "orphaned", source: null }; const match = matches[0]!; return { resolution: "relocated", source: { ...annotation.source, path: match.path, line: match.line, endLine: match.line, snippet: match.snippet, evidence: `Relocated by unique source-line hash from ${annotation.source.path}:${annotation.source.line}` } }; };

  async function load(filter: { route?: string; checkpointId?: string | null } = {}): Promise<AnnotationState> {
    const folder = await directory(); const entries = await ops.readdir(folder, { withFileTypes: true }); const views: AnnotationView[] = []; const valid: Array<{ file: string; annotation: Annotation }> = []; const files = entries.filter((entry) => entry.name.endsWith(".json") && !entry.name.startsWith(".")).sort((a, b) => a.name.localeCompare(b.name));
    await Promise.all(files.map(async (entry) => { const view = { file: entry.name, annotation: null, resolution: "invalid" as const, resolvedSource: null, checkpointRelationship: "current" as const }; try { if (!entry.isFile() || entry.isSymbolicLink()) throw new Error("ANNOTATION_FILE_UNSAFE"); const raw = String(await ops.readFile(path.join(folder, entry.name), "utf8")); if (/^(?:<<<<<<<|=======|>>>>>>>)/m.test(raw)) throw new Error("ANNOTATION_GIT_CONFLICT"); valid.push({ file: entry.name, annotation: validateAnnotation(JSON.parse(raw)) }); } catch (error) { const code = error instanceof Error ? error.message : String(error); views.push({ ...view, resolution: code === "ANNOTATION_VERSION_UNSUPPORTED" ? "unsupported" : "invalid", error: code }); } })); valid.sort((a, b) => a.file.localeCompare(b.file)); views.sort((a, b) => a.file.localeCompare(b.file));
    const duplicates = new Set(valid.filter((item, index) => valid.findIndex((candidate) => candidate.annotation.id === item.annotation.id) !== index).map((item) => item.annotation.id)); const lines = new Map<string, string[]>(); const moved: { index?: Map<string, Array<{ path: string; line: number; snippet: string }>> } = {};
    for (const item of valid) { const relation = filter.checkpointId === undefined || filter.checkpointId === null ? "current" : item.annotation.relatedCheckpoint === filter.checkpointId ? "related" : "other"; if (duplicates.has(item.annotation.id)) views.push({ file: item.file, annotation: item.annotation, resolution: "conflict", resolvedSource: null, checkpointRelationship: relation, error: `ANNOTATION_ID_DUPLICATE:${valid.filter((candidate) => candidate.annotation.id === item.annotation.id).map((candidate) => candidate.file).join(",")}` }); else { const resolved = await resolve(item.annotation, lines, moved); views.push({ file: item.file, annotation: item.annotation, resolution: resolved.resolution, resolvedSource: resolved.source, checkpointRelationship: relation }); } }
    views.sort((a, b) => a.file.localeCompare(b.file)); const annotations = views.filter((item) => item.annotation && (!filter.route || item.annotation.route === filter.route)); const current = annotations.filter((item) => item.checkpointRelationship !== "other"); return { annotations, issues: views.filter((item) => item.resolution !== "exact" && item.resolution !== "relocated"), parsedFiles: files.length, renderedForRoute: current.filter((item) => item.resolution === "exact" || item.resolution === "relocated").length };
  }

  async function create(draft: AnnotationDraft): Promise<Annotation> { validateDraft(draft); const now = options.now?.() ?? new Date().toISOString(); const id = (options.createId?.() ?? randomUUID()).toLowerCase(); if (!uuidPattern.test(id)) throw new Error("ANNOTATION_ID_INVALID"); const line = await snippetAt(draft.source.path, draft.source.line); const annotation: Annotation = { schemaVersion, id, kind: "comment", author: draft.author.trim(), createdAt: now, updatedAt: now, component: draft.component.trim(), fingerprint: draft.fingerprint, source: { ...line, endLine: draft.source.endLine ?? line.line, evidence: draft.source.evidence }, route: draft.route, viewport: draft.viewport, comment: draft.comment.trim(), replies: [], highlight: draft.highlight ?? null, imagePath: null, position: null, status: "open", relatedCheckpoint: draft.relatedCheckpoint ?? null, relatedDesignDna: draft.relatedDesignDna ?? null, anchorConfidence: draft.anchorConfidence, history: [{ action: "created", at: now }] }; validateAnnotation(annotation); await atomicCreate(await annotationFile(id), `${JSON.stringify(annotation, null, 2)}\n`); return annotation; }
  async function createImage(draft: ImageAnnotationDraft): Promise<Annotation> { if (!route(draft.route) || !viewport(draft.viewport) || !position(draft.position) || !relativePath(draft.imagePath)) throw new Error("ANNOTATION_IMAGE_DRAFT_INVALID"); const now = options.now?.() ?? new Date().toISOString(); const id = (draft.id ?? options.createId?.() ?? randomUUID()).toLowerCase(); if (!uuidPattern.test(id)) throw new Error("ANNOTATION_ID_INVALID"); const snippet = "<!-- reframe image annotation -->"; const annotation: Annotation = { schemaVersion, id, kind: "image", author: (draft.author ?? "Local reviewer").trim().slice(0, 128), createdAt: now, updatedAt: now, component: "page", fingerprint: { tag: "body", id: null, classes: [], text: "", parent: null, route: draft.route, viewport: draft.viewport }, source: { path: "index.html", line: 1, endLine: 1, snippet, hash: sha256(snippet), evidence: "Pasted image overlay" }, route: draft.route, viewport: draft.viewport, comment: "(pasted image)", replies: [], highlight: null, imagePath: normalize(draft.imagePath), position: draft.position, status: "open", relatedCheckpoint: null, relatedDesignDna: null, anchorConfidence: "exact", history: [{ action: "created", at: now }] }; validateAnnotation(annotation); await atomicCreate(await annotationFile(id), `${JSON.stringify(annotation, null, 2)}\n`); return annotation; }
  const imageDirectory = () => directory().then((folder) => path.join(path.dirname(folder), "annotation-images"));
  async function readImage(id: string): Promise<Buffer> { if (!uuidPattern.test(id)) throw new Error("ANNOTATION_ID_INVALID"); const root = await project(); const folder = await imageDirectory(); const file = path.join(folder, `${id.toLowerCase()}.png`); const resolved = await ops.realpath(file); if (!inside(root, resolved)) throw new Error("ANNOTATION_PATH_ESCAPE"); return Buffer.from(await ops.readFile(resolved)); }
  async function saveImage(id: string, bytes: Uint8Array): Promise<string> { if (!uuidPattern.test(id)) throw new Error("ANNOTATION_ID_INVALID"); if (!bytes.byteLength || bytes.byteLength > 8 * 1024 * 1024) throw new Error("ANNOTATION_IMAGE_TOO_LARGE"); const root = await project(); const folder = await ops.realpath(await imageDirectory().then(async (target) => { await ops.mkdir(target, { recursive: true }); return target; })); if (!inside(root, folder)) throw new Error("ANNOTATION_PATH_ESCAPE"); const file = path.join(folder, `${id.toLowerCase()}.png`); const temporary = path.join(folder, `.${id}.${randomUUID()}.tmp`); const handle = await ops.open(temporary, "wx"); try { await handle.writeFile(bytes); await handle.sync(); } finally { await handle.close(); } await ops.rename(temporary, file); return normalize(path.relative(path.join(root, ".reframe"), file)); }
  async function update(id: string, action: "resolve" | "reopen"): Promise<Annotation> { const file = await annotationFile(id); const annotation = validateAnnotation(JSON.parse(String(await ops.readFile(file, "utf8")))); const status: AnnotationStatus = action === "resolve" ? "resolved" : "open"; const now = options.now?.() ?? new Date().toISOString(); const updated: Annotation = { ...annotation, status, updatedAt: now, history: [...annotation.history, { action: action === "resolve" ? "resolved" : "reopened", at: now }] }; await atomicReplace(file, `${JSON.stringify(updated, null, 2)}\n`); return updated; }
  async function updateImage(id: string, patch: { position: AnnotationPosition }): Promise<Annotation> { if (!position(patch.position)) throw new Error("ANNOTATION_IMAGE_DRAFT_INVALID"); const file = await annotationFile(id); const annotation = validateAnnotation(JSON.parse(String(await ops.readFile(file, "utf8")))); if (annotation.kind !== "image") throw new Error("ANNOTATION_NOT_IMAGE"); const now = options.now?.() ?? new Date().toISOString(); const updated: Annotation = { ...annotation, position: patch.position, updatedAt: now }; validateAnnotation(updated); await atomicReplace(file, `${JSON.stringify(updated, null, 2)}\n`); return updated; }
  async function deleteImage(id: string): Promise<void> { const file = await annotationFile(id); const annotation = validateAnnotation(JSON.parse(String(await ops.readFile(file, "utf8")))); if (annotation.kind !== "image") throw new Error("ANNOTATION_NOT_IMAGE"); await ops.rm(file); if (annotation.imagePath) { const root = await project(); const imageFile = path.resolve(root, ".reframe", annotation.imagePath); if (inside(root, imageFile)) await ops.rm(imageFile, { force: true }).catch(() => undefined); } }
  async function promote(id: string, confirmed: boolean): Promise<DesignDnaProposal> { if (!confirmed) throw new Error("DESIGN_DNA_CONFIRMATION_REQUIRED"); const annotation = validateAnnotation(JSON.parse(String(await ops.readFile(await annotationFile(id), "utf8")))); const proposal: DesignDnaProposal = { schemaVersion: 1, id: `dna-proposal-${randomUUID()}`, annotationId: id, createdAt: options.now?.() ?? new Date().toISOString(), status: "needs-review", rule: annotation.comment, scope: { component: annotation.component, sourcePath: annotation.source.path, route: annotation.route } }; const folder = path.join(await project(), ".reframe", "design-dna", "proposals"); await ops.mkdir(folder, { recursive: true }); const resolved = await ops.realpath(folder); if (!inside(await project(), resolved)) throw new Error("DESIGN_DNA_PATH_ESCAPE"); await atomicCreate(path.join(resolved, `${proposal.id}.json`), `${JSON.stringify(proposal, null, 2)}\n`); return proposal; }
  async function subscribe(listener: (state: AnnotationState) => void | Promise<void>, filter: { route?: string; checkpointId?: string | null } = {}): Promise<() => void> { const folder = await directory(); let timer: NodeJS.Timeout | undefined; let closed = false; const watcher = watch(folder, () => { clearTimeout(timer); timer = setTimeout(() => { if (!closed) void load(filter).then(listener); }, options.watcherDebounceMs ?? 75); }); watchers.add(watcher); return () => { closed = true; clearTimeout(timer); watcher.close(); watchers.delete(watcher); }; }
  async function close() { for (const watcher of watchers) watcher.close(); watchers.clear(); }
  return { create, createImage, saveImage, readImage, update, updateImage, deleteImage, load, promote, subscribe, close, directory: annotationDirectory };
}
